[package]
name = "chetan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "chetan"
crate-type = ["cdylib"]

[dependencies]
primitive-types = "0.13.1"
pyo3 = "0.25"
